#!/bin/bash
#Florian / Adrien

#vérification des droits d'administrateur
if [ "$USER" != "root" ]
	then
		echo "Cette opération nécessite les droits d'administrateur."
else

#début du script
echo "Installation d'Atom, veuillez patientez..."
apt-get -qq update
apt-get -qq install gdebi

#boucle
while [ "$rep1" != "Y" ] && [ "$rep1" != "N" ];
	do
		echo "installer le paquet logiciel ?"
		read rep1
done
#fin de boucle

if [ "$rep1" == "Y" ];
	then
		wget --show-progress -q -P /home/$USERNAME/Téléchargements https://github.com/atom/atom/releases/download/v1.24.0/atom-amd64.deb
		while [ "$rep2" != "Y" ] && [ "$rep2" != "N" ];
			do
				echo "Lancer l'installation ?"
				read rep2
			done

			if [ "$rep2" == "Y" ];
				then
					gdebi /home/$USERNAME/Téléchargements/atom-amd64.deb
			elif [ "$rep2" == "N" ];
				then
					echo "Annulation ..."
			else
				echo "Argument incorrect"
			fi

elif [ "$rep1" == "N" ]
	then
		while [ "$rep2" != "Y" ] && [ "$rep2" != "N" ];
			do
				echo "Lancer l'installation ?"
				read rep2
			done

			if [ "$rep2" == "Y" ];
				then
					gdebi /atom-amd64.deb
			elif [ "$rep2" == "N" ];
				then
					echo "Annulation ..."
			else
				echo "Argument incorrect"
			fi
else
	echo "erreur"
fi

fi
