#!/bin/bash
#Florian / Adrien
echo "Installation d'Atom, veuillez patientez..."
apt-get update
apt-get install gdebi

while [ $rep1 != "Y" || "N" ];
	do
		echo "installer le paquet logiciel ?"
		read rep1
done

if [ "$rep1" == "Y" ];
	then
		wget https://github.com/atom/atom/releases/download/v1.24.0/atom-amd64.deb
else
	echo "Lancer l'installation ?"
	read rep2

		if [ "$rep2" == "Y" ];
			then 
				gdebi /atom-amd64.deb
		elif [ "$rep2" == "N" ];
			then 
				echo "Annulation ..."
		else 
			echo "Argument incorrect"
		fi
fi
